name: Deploy React + Vite to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     #setup nodejs   

        name: setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version:18

#install Dependancies 
        name: install Dependancies
        run: npm install

#build Project Dependancy
        name: install Dependancies
        run: npm run build

#deploy to github pages
        name : Deploy to github pages
        uses : peaceiris/actions-gh-pages@v3
        with : 
               github_token : ${{ secrets.GITHUB_TOKEN }}
               publish_dir : dist
        